demo: &demo
  docker:
    - image: circleci/node:8.11.3

version: 2
jobs:
  build:
    <<: *demo
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
      # Save artifacts
      - type: store_test_results
        path: test-results
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
