demo: &demo
  docker:
    - image: circleci/node:8.11.3

version: 2
jobs:
  build:
    <<: *demo
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - store_test_results:
          path: ~/test-results
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
      # Save test-results
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit    
  #    - store_artifacts:
  #        path: test/junit/test-results.xml
  #        destination: test-results
  #    - store_test_results:
  #        path: test
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
